### ISSUE TITLE
Smooth transitioned elements not working on Firefox

### ISSUE THREAD

**Issue by DominikSerafin** [diegoversiani/smooth-parallax#2]
Hi Diego!

Love the plugin. It has what other parallax plugin don't have - smooth transitions on scroll end.

Like those clouds in the demo: https://diegoversiani.me/smooth-parallax/

Unfortunately this one specific feature doesn't work in Firefox (Quantum) and also breaks the element movement entirely.

It works on Chrome, Edge, IE 11 and Safari, though - so that's nice.

**Comment by diegoversiani** [comment]
Hi Dominik,

I'm glad you like it :) and thanks for opening the issue.

It happens actually due to an issue with Firefox not being able to calculate svg sizes with `scrollWidth` and `scrollHeight`.

I fixed it adding a fallback to use `window.getComputedStyle` and released a [new version v1.1.2](https://github.com/diegoversiani/smooth-parallax/tree/v1.1.2) which is also available via npm and bower.

Tested in Chrome, Safari, Opera and Firefox (latest).
Didn't test on IE or Edge, would you do that favor?

Have a nice one,
